author: Andrew Lazarus <nerdrew@gmail.com>
homepage: https://github.com/nerdrew/dart-ctags
description: ctags compatible tag file generator for dart code
name: dart_ctags
version: 1.0.0
environment:
    sdk: ">=2.0.0 <3.0.0"
executables:
    dart_ctags: tags
dependencies:
    analyzer: ^0.39.0
    path: ^1.0.0
    quiver: ^2.0.0
    args: ^1.0.0
dev_dependencies:
    pedantic: ^1.0.0
